//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activities()
        {
            this.Documents = new HashSet<Documents>();
        }
    
        public int ActivityId { get; set; }
        public string ActivityName { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public string Description { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public int ActivityTypeId { get; set; }
        public string Color { get; set; }
    
        public virtual ActivityTypes ActivityTypes { get; set; }
        public virtual Modules Modules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documents> Documents { get; set; }
    }
}
