//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int DocumentId { get; set; }
        public string DocumentName { get; set; }
        public System.DateTime UploadingTime { get; set; }
        public string DocumentRef { get; set; }
        public string DocumentFileType { get; set; }
        public byte[] FileData { get; set; }
        public string FeedBack { get; set; }
        public bool isHomework { get; set; }
        public string Description { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public string ApplicationUserId { get; set; }
    
        public virtual Activities Activities { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Courses Courses { get; set; }
        public virtual Modules Modules { get; set; }
    }
}
